server:
  port: 8080
  readTimeout: 5s
  writeTimeout: 10s
  idleTimeout: 15s
  maxHeaderBytes: 1048576 # 1MB

log:
  level: info # debug, info, warn, error

checksum:
  maxInputLengthBytes: 1048576 # 1MB
  maxFileUploadSizeMB: 10 # 10MB

telegram:
  enabled: true # 启用/禁用 Telegram 通知
  botToken: "8157774237:AAGMrGHHhemaoJYtb6rBUkjz8Nyvt7QwAZM" # 从 @BotFather 获取
  chatId: "7943067576" # 从 @userinfobot 获取
  timeout: 5s # 通知请求超时时间
